name: Vulnerabilities

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '23 3 * * 6'

jobs:
  analyse:
    uses: clambin/workflows/.github/workflows/vulnerabilities.yaml@main
